# Generated by Django 5.1.5 on 2025-03-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_project_alter_event_category_alter_event_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
    ]
