# Generated by Django 5.1.5 on 2025-01-26 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_employee_event_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='events.event'),
        ),
    ]
