# Generated by Django 5.1.5 on 2025-01-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventdetail_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='assigned_to',
            field=models.ManyToManyField(related_name='events', to='events.employee'),
        ),
    ]
